### ISSUE TITLE
Oracle JDK?

### ISSUE THREAD

**Issue by gorzell** [Netflix-Skunkworks/zerotodocker#33]
I am curious why you guys chose to use the Oracle JDK which some would consider license heavy, especially since you accept on behalf of everyone rather than using openjdk or the Azul version of openjdk?

**Comment by aspyker** [comment]
We used the Oracle JDK as it is the one Netflix runs on.  I know from personal experience that with minor changes most of the NetflixOSS works on the IBM JDK.  However, we don't frequently test on openjdk and I don't know of any time we have run on Azul.  The place where we noticed difference was mostly in the groovy implementations,
